import argparse
def ParseArgs():
    parser = argparse.ArgumentParser(description='Model Params')
    parser.add_argument('--seed', type=int, default=2024, help='Random seed')
    parser.add_argument('--lr', default=5e-4, type=float, help='learning rate')  
    parser.add_argument('--batch', default=16384, type=int, help='batch size')  
    parser.add_argument('--device',default='cuda', type=str, help='cuda or cpu')
    parser.add_argument('--tstBat', default=128, type=int, help='number of users in a testing batch')
    parser.add_argument('--epoch', default=200, type=int, help='number of epochs')  
    parser.add_argument('--save_path', default='tem', help='file name to save model and training record')
    parser.add_argument('--latdim', default=128, type=int, help='embedding size')
    parser.add_argument('--load_model', default=None, help='model name to load')
    parser.add_argument('--topk', default=20, type=int, help='K of top K')
    parser.add_argument('--num_gnn_layers', default=4, type=float, help='number of gnn layers')
    parser.add_argument('--num_mamba_layers', default=4, type=float, help='number of mamba layers')
    parser.add_argument('--data', default='tmall', type=str, help='name of dataset')
    parser.add_argument('--tstEpoch', default=2, type=int, help='number of epoch to test while training')
    parser.add_argument('--gpu', default='0', type=str, help='indicates which gpu to use')  
    parser.add_argument('--dropout', default=0.4, type=float, help='Ratio of transformer layer dropout')  
    parser.add_argument('--layer_cl', default=3, type=int, help='layer_cl')  
    parser.add_argument('--lambda_cl', default=0.2, type=float, help='lambda')  
    parser.add_argument('--tau', default=0.2, type=float, help='tau')  
    parser.add_argument('--eps', default=0.2, type=float, help='eps')
    parser.add_argument('--reg', default=1e-4, type=float) 
    parser.add_argument('--d_state', default=16, type=int, help='SSM state expansion factor')
    parser.add_argument('--d_conv', default=4, type=int, help='Local convolution width')
    parser.add_argument('--expand', default=2, type=int, help='Block expansion factor')
    return parser.parse_args()
args = ParseArgs()

