import argparse
def ParseArgs():
    parser = argparse.ArgumentParser(description="LMGNN family hyper-parameters")
    parser.add_argument("--seed",           type=int,   default=2025,   help="Random seed")
    parser.add_argument("--lr",             type=float, default=8e-4,   help="Learning Rate")
    parser.add_argument("--batch",          type=int,   default=8192,   help="Batch Size")
    parser.add_argument("--device",         type=str,   default="cuda", help="cuda / cpu")
    parser.add_argument("--epoch",          type=int,   default=200,    help="Training epochs")
    parser.add_argument("--tstBat",         type=int,   default=128,    help="Test Batch Size")
    parser.add_argument("--tstEpoch",       type=int,   default=1,      help="Number of epoch to test while training")
    parser.add_argument("--save_path",      type=str,   default="tem",  help="File name to save model and training record")
    parser.add_argument("--gpu",            type=str,   default="0",    help="GPU ID to use")
    parser.add_argument('--load_model',                 default=None,   help='Model name to load')
    parser.add_argument("--data",           type=str, default="yelp",   help="Name of Dataset")
    parser.add_argument("--latdim",         type=int, default=160,       help="embedding size")
    parser.add_argument("--num_gnn_layers", type=int,   default=4,      help="GNN Layers")
    parser.add_argument("--num_mamba_layers", type=int, default=2,      help="Mamba layers")
    parser.add_argument("--dropout", type=float, default=0.4,           help="Dropout rate")
    parser.add_argument("--d_state",         type=int,   default=20,     help="Hidden state size of Mamba")
    parser.add_argument("--d_conv",          type=int,   default=4,     help="Mamba convolution channel size")
    parser.add_argument("--expand",          type=int,   default=8,     help="Mamba expansion factor")
    parser.add_argument("--layer_cl",        type=int,   default=3,     help="Number of layers for ALCA")
    parser.add_argument("--lambda_cl",       type=float, default=0.05,   help="CL rate")
    parser.add_argument("--tau",             type=float, default=0.2,   help="Temperature for contrastive loss")
    parser.add_argument("--reg",             type=float, default=1e-4,  help="L2 regularization")
    parser.add_argument("--topk", nargs="+", type=int, default=[20, 40], help="Top K for evaluation")
    return parser.parse_args()
args = ParseArgs()

