import argparse
def ParseArgs():
    parser = argparse.ArgumentParser(description="LMGNN family hyper-parameters")
    parser.add_argument("--seed",            type=int,   default=2024,   help="Random seed")
    parser.add_argument("--lr",              type=float, default=1e-3,   help="Learning Rate")
    parser.add_argument("--batch",           type=int,   default=8192,   help="Batch Size")
    parser.add_argument("--device",          type=str,   default="cuda", help="cuda / cpu")
    parser.add_argument("--epoch",           type=int,   default=200,    help="Training epochs")
    parser.add_argument("--tstBat",          type=int,   default=256,    help="Test Batch Size")
    parser.add_argument("--tstEpoch",        type=int,   default=1,      help="Number of epoch to test while training")
    parser.add_argument("--save_path",       type=str,   default="tem",  help="File name to save model and training record")
    parser.add_argument("--logPath",         type=str,   default="./History",  help="Path to save logs")
    parser.add_argument("--gpu",             type=str,   default="0",    help="GPU ID to use")
    parser.add_argument('--load_model',                  default=None,   help='Model name to load')
    parser.add_argument("--data",            type=str,   default="yelp",   help="Name of Dataset")
    parser.add_argument("--latdim",          type=int,   default=64,      help="embedding size")
    parser.add_argument("--num_gnn_layers",  type=int,   default=1,      help="GNN Layers")
    parser.add_argument("--num_mamba_layers", type=int,  default=1,      help="Mamba layers")
    parser.add_argument("--dropout",         type=float, default=0.4,           help="Dropout rate")
    parser.add_argument("--d_state",         type=int,   default=8,    help="Hidden state size of Mamba")
    parser.add_argument("--d_conv",          type=int,   default=4,     help="Mamba convolution channel size")
    parser.add_argument("--expand",          type=int,   default=2,     help="Mamba expansion factor")

    parser.add_argument("--gate_dim",        type=int,   default=16,     help="gate_dim")
    parser.add_argument("--gate_temp",       type=float, default=0.8,  help="yelp:0.8  tmall:0.8")
    parser.add_argument("--depth_noise",     type=float, default=0.05,  help="yelp:0.05  tmall:0.05")
    parser.add_argument("--gate_adv_eps",    type=float, default=0.1,  help="yelp:0.1  tmall:0.25")
    parser.add_argument("--lambda_cl",       type=float, default=0.04,  help="CL rate, Yelp:0.04 Tmall:0.04")
    parser.add_argument("--tau",             type=float, default=0.2,   help="Temperature for contrastive loss, Yelp: 0.2 Tmall: 0.15")
    parser.add_argument("--cl_neg_samples",  type=int,   default=2048,  help="Number of negatives per sample for CL (0=full)")
    parser.add_argument("--cl_mix_uniform",  type=float, default=0.2,  help="Mix ratio for uniform vs weighted sampling in CL")
    parser.add_argument("--cl_pop_beta",     type=float, default=0.5,  help="Exponent for popularity weights in CL sampling")
    parser.add_argument("--cl_strata_bins",  type=int,   default=4,    help="Number of strata for sampling (0=off)")
    parser.add_argument("--cl_strata_uniform", type=float, default=0.8, help="Uniform ratio inside each stratum")
    parser.add_argument("--reg",             type=float, default=1e-4,  help="L2 regularization")
    parser.add_argument("--topk", nargs="+", type=int, default=[20, 40], help="Top K for evaluation")
    parser.add_argument("--early_stop_patience", type=int, default=15, help="Early stopping patience (0=off)")
    parser.add_argument("--early_stop_min_delta", type=float, default=1e-4, help="Minimum improvement to reset early stop")
    return parser.parse_args()
args = ParseArgs()


